version: 0.2

env:
  variables:
    ApiGatewayInvokeUrl: " "
    LambdaFunctionName: " "
    LambdaFunctionAlias: " "
  parameter-store:
    api_key: "/portfolio/CICD/integration_tests_APIGateway_API_key"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g newman
  
  pre_build:
    commands:
      # Add the API key to the Postman collections template
      #- sed -i "s/api_gateway_api_key/${api_key}/"  
      #    LinearEquationSolverIntegrationRequireAPIKey.postman_collection_template.json
      - python configure_postman_collection.py $ApiGatewayInvokeUrl $LambdaFunctionAlias $api_key
          
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date` from dir `pwd`
      - newman run 
          LinearEquationSolverIntegrationRequireAPIKey.postman_collection.json 
          -r junit,cli
          --reporter-html-export apireport.html
          --delay-request 10
          -d $CODEBUILD_SRC_DIR_EqnSolverSourceCode/integration_tests/TestCases.json

      
      - ls 

  post_build:
    commands:
      - python create_appspec.py $LambdaFunctionName $LambdaFunctionAlias 
          "AppSpec.yaml" 
          $AWS_ACCOUNT_ID 
          $AWS_DEFAULT_REGION


reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'newman' # Location of the reports

artifacts:
  files:
    - AppSpec.yaml
  name: EquationSolverTestReports
  discard-paths: no
  base-directory: "./"
  secondary-artifacts:
    ProductionAppSpecFile:
      files:
        - AppSpec.yaml
      name: ProductionAppSpecFile
      discard-paths: no
      base-directory: "./"
    NewmanIntegrationTestsReport:
      files:
        - 
      name: NewmanIntegrationTestsReport
      discard-paths: no
      base-directory: "./newman"

